services:
  db:
    image: postgres:16-alpine3.19
    container_name: watch-over-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - watchover-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # app:
  #   environment:
  #     - REDIS_URL=redis://redis_dev:6379
  #     - NODE_ENV=development
  #     - DATABASE_URL
  #   container_name: watch-over-comments
  #   image: mrglox/nestjs-remix-monorepo:dev
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   networks:
  #     - watchover-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: [ "redis-server" ]
    # --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./cache:/data
      - /dev/volumes/nestjs-remix/dev/sessions/:/data

volumes:
  postgres_data:


networks:
  watchover-network:
    driver: bridge
